version: '3.1'

services:
  postgres:
    build: ./src/db
    image: postgres:11
    container_name: "mint-data-postgres"
    ports:
      - 5432:5432
    volumes:
      - ./data:/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  data-volume: